name: CI - build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
            with:
            version: 7.29.1

      - name: run Build
        run: |
          pnpm install
          pnpm run build
