name: CI - lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-18.04
    name: Lint    

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
          with:
          version: 7.29.1

      - name: run Lint
        run: |
          pnpm install
          pnpm run lint
