name: CI - test

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    name: Test    

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
          with:
          version: 7.29.1

      - name: run Test
        run: |
          pnpm install
          pnpm run test